### PR TITLE
Fixes in saas_portal_start and saas_portal_signup

### PR DESCRIPTION
**Pull request by kaerdsar**
Now in saas_portal_start I use the first confirmed saas_portal.plan to create a new client. Maybe we need something better.

### CODE REVIEW

**Comment by yelizariev** [comment]
Thank you.

What do you think about saas_pricing? 
I look through and noted stripe field. Is it about https://stripe.com/ ?
If so, I think some renaming of the module should be done like saas_pricing_base and saas_pricing_stripe?
If we anyway need to make renames, then we probably could  delete saas_pricing and return updated version latter?

**Comment by kaerdsar** [comment]
Yes, saas_pricing is about stripe, so you are right about create a 
saas_pricing_base and later many saas_pricing_xxx.

The current saas_pricing module is not good enough.

**Comment by yelizariev** [comment]
Probably saas_pricing_base module could be just saas_pricing -- like we've done for saas_sysadmin

**Comment by cmsalmeida** [comment]
I agree in leaving the saas_pricing as the base one.
Also because you already did the same to saas_sysadmin, same aproach...

**Pull request merged**
