### PR TITLE
WIP Travis ci integration

### PR DESCRIPTION
**Pull request by cmsalmeida**
The travis configuration is ok, but it gives errors installing some of the modules.

The travis integration will build and run Odoo tests, in both OCA/OCB and Odoo/Odoo repositories.

What is your suggestion to do:
 1. add travis.yml any way accepting this PR?
 2. make the required  fixes in this branch in order to travis build without errors, and then accept PR?

### CODE REVIEW

**Comment by cmsalmeida** [comment]
The lint is inactive, for now, don't even tried, but should be good to activate it in short future
After travis file activated, I can do the clean in a PR

**Comment by yelizariev** [comment]
I have never used travis.yml. 
You can just add travis.yml or make fixes too. Decide yourself.

**Comment by cmsalmeida** [comment]
Ok i'll add travis and will do the pep8 fixes in order to pass all tests.

**Comment by yelizariev** [comment]
Thank you. Let's try it

**Pull request merged**
