### PR TITLE
[IMP] Stop clients from opting into critical groups

### PR DESCRIPTION
**Pull request by tarzan0820**
Hides the following Checkboxes - 'Technical Features', 'Multi Companies', 'Show Modules Menu',
stopping clients from bypass security restrictions or messing up their DB by modifying technical details.

### CODE REVIEW

**Comment by saltonmassally** [comment]
@yelizariev  We can add an ir_config.parameter that we can first check for before hiding these check-boxes enabling us to conditionally present these checkboxes... what are your thoughts on thisi

**Comment by yelizariev** [comment]
@tarzan0820 
- It is right, that we have to hide 'Show Modules Menu' tick, because without such update we cannot give to user access to Settings\Users menu
- I don't see a problem with  'Multi Companies' tick. I think it should be shown by default
- I don't like idea to filter ticks by names. Strong reference should be used instead.
- I think we can create special settings, where superuser can configure list of ticks that have to be hidden from usual user
- I am not sure about way to organize relationship between saas and web_debranding. Probably it could be as follows:
  - "hide access ticks" is implemented as a new module (in addons-yelizariev repo)
  - new module is added as dependencies to web_debranding
  - **SaaS modules doesn't have such settings by default, so superuser (SaaS provider) has to hide Settings menu  from customer users.**
  - superuser (SaaS provider) has to install web_debranding to be flexible on access to Settings
  - probable "Show modules" menu could be moved from web_debranding to the new module, say web_admin_limited (which will have "hide access ticks" feature too). So it would be possible to have  flexible options on access to Settings without debranding, but web_admin_limited will be added to web_debranding module, of course.

Let me know what do you think about it

@kaerdsar  @nicholas-itpedia this could be interesting for you too

**Comment by yelizariev** [comment]
One more thing. It seems, that if we only hide ticks, it would be still possible to tick access rights directly via odoo API. So, some extra checks should be added. But I think just hiding ticks is enough for first time.

**Comment by yelizariev** [comment]
@tarzan0820 

Check this example how to implement interface for selecting list of ticks to hide
https://github.com/yelizariev/addons-yelizariev/blob/8.0/mail_move_message/mail_move_message_models.py#L306-L329

(you need to use res.groups instead ir.model)

**Comment by saltonmassally** [comment]
@yelizariev I agree with your reasoning; I have being waiting for the others to weigh in before doing this but I will make the necessary adjustments and update PR

**Comment by saltonmassally** [comment]
@yelizariev on second thoughts I think since the objective of this is to restrict users opting into certain groups the addon should be called restricted_groups.... which by definition can be groups that no one except superadmin or other privileged groups can opt into

**Comment by saltonmassally** [comment]
Also rather than Introducing this as a setting what about the following:
- Add as boolean field to re.group (this can be ticked from the group form if it should be restricted)
- Check for value of this field before checkboxes are shown to users
- We can also use this field to ensure that users do not add themselves via the api
  Let  me get your thoughts

**Comment by yelizariev** [comment]
I suggest res_groups_restricted name. It a common way to start module with a base model what is inherited (web_..., res_users_... etc)

> Add as boolean field to res.group (this can be ticked from the group form if it should be restricted)

Right, this an alternative way. I prefer my way, because it allows to mark all resctricted groups quickly. But you can implement your way. Don't forget to restrict access to such tick too.

> We can also use this field to ensure that users do not add themselves via the api Let me get your thoughts

Probably, you can override write function to check access rights

**Comment by yelizariev** [comment]
Another idea to restrict groups: All users (except superuser) have access only to groups he already have.  I.e., user cannot extend rights he already have. Only Superuser can do it. Usual user can only restrict his rights or modify other users rights but not more he has himself.

**Comment by yelizariev** [comment]
Let's continue discussion here: https://github.com/yelizariev/odoo-saas-tools/issues/51

**Pull request closed without merging**
