### PR TITLE
saas_portal: multi config databases

### PR DESCRIPTION
**Pull request by tarzan0820**
adds the ability to configure multiple databases at the same time

### CODE REVIEW

**Comment by yelizariev** [comment]
I think it's a time to implement runbot for saas))

**Comment by yelizariev** [comment]
I think some other parts of code call do_upgrade_database. We need to check it.

@iledarn

**Comment by cmsalmeida** [comment]
I've done the integration with Travis via OCA tools.
We just need to get it passing the tests.
Check #104 PR

**Comment by yelizariev** [comment]
@cmsalmeida I meant a runbot, that will deploy system via saas.py

**Comment by saltonmassally** [comment]
@yelizariev any more thoughts on this?

**Comment by yelizariev** [comment]
@iledarn shall check it first

**Comment by iledarn** [comment]
@yelizariev, it is ok

**Pull request merged**
