### PR TITLE
[IMP] saas server backup

### PR DESCRIPTION
**Pull request by tarzan0820**
* Add a cron job that deletes old database backups
* change implementation of 'backup_database' to use self.ensure_one

### CODE REVIEW

**Comment by saltonmassally** [comment]
@iledarn pls take look at this

**Comment by yelizariev** [comment]
My comments:
- how to configure unlimited backups?
- what about more flexible backup rotation: https://github.com/xolox/python-rotate-backups
- what about moving cron to a separate module (say, saas_server_backup_rotate) as we done with saas_server_autodelete

**Comment by yelizariev** [comment]
Also, I don't think that this is a good idea

```
     @api.multi
      def backup_database(self):
+         self.ensure_one()
```

How can you be sure that there is only one record in recordset?

**Comment by saltonmassally** [comment]
@yelizariev 

Unlimited configuration is not supported, guess you can do this by putting a rather large number in the existing configuration fields, I can add support for that

 https://github.com/xolox/python-rotate-backups looks good, I think we can support the configuration style, but the actual implementation will have to depend on the storage being used, e.g. s3 or local disk

ok will move to saas_server_backup_rotate

My reason for doing @api.multi was that one can only evoke it for a client at a time from the portal but it is just occurring to me that might not be the only use case so I guess you are right

**Comment by saltonmassally** [comment]
@yelizariev here we go... effected your suggestions, review when u r chanced

**Comment by yelizariev** [comment]
Ok, thanks. I can accept this PR and make new issue about my concerns

**Comment by yelizariev** [comment]
https://github.com/yelizariev/odoo-saas-tools/issues/239

**Pull request merged**
