### PR TITLE
Create install-odoo-saas

### PR DESCRIPTION
**Pull request by bassn**
A small contribution to that great work

### CODE REVIEW

**Comment by yelizariev** [comment]
Nice, thanks for sharing

**Comment by yelizariev** [comment]
I am thinking about moving that script from gist to github to make branches for different OS etc.

**Comment by bassn** [comment]
Good idea, this would bring even more flexibility. Feel free to do so...

**Comment by yelizariev** [comment]
I have moved scripts to github repo: https://github.com/yelizariev/install-odoo and created TODO https://github.com/yelizariev/install-odoo/issues/1

**Comment by LiberTang0** [comment]
the script install-odoo-saas don't work even on odoo 8.0 and 9.0

`

Odoo Server Error

Traceback (most recent call last):
  File "/usr/local/src/odoo/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/src/odoo/openerp/http.py", line 576, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/local/src/odoo/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/local/src/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/local/src/odoo/openerp/http.py", line 309, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/local/src/odoo/openerp/http.py", line 805, in __call__
    return self.method(_args, *_kw)
  File "/usr/local/src/odoo/openerp/http.py", line 405, in response_wrap
    response = f(_args, *_kw)
  File "/usr/local/src/odoo/addons/web/controllers/main.py", line 1247, in load
    action = request.session.model(action_type).read([action_id], False, ctx)
  File "/usr/local/src/odoo/openerp/http.py", line 910, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/usr/local/src/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/local/src/odoo/openerp/addons/base/ir/ir_actions.py", line 326, in read
    results = super(ir_actions_act_window, self).read(cr, uid, ids, fields=fields, context=context, load=load)
  File "/usr/local/src/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/local/src/odoo/openerp/models.py", line 3144, in read
    result = BaseModel.read(records, fields, load=load)
  File "/usr/local/src/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/local/src/odoo/openerp/models.py", line 3179, in read
    self._read_from_database(stored, inherited)
  File "/usr/local/src/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/local/src/odoo/openerp/models.py", line 3366, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/usr/local/src/odoo/openerp/osv/fields.py", line 1460, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/usr/local/src/odoo/openerp/addons/base/ir/ir_actions.py", line 266, in _search_view
    field_get = self.pool[act.res_model].fields_view_get(cr, uid,
  File "/usr/local/src/odoo/openerp/modules/registry.py", line 102, in __getitem__
    return self.models[model_name]
KeyError: u'saas_portal.client'

`

**Comment by bassn** [comment]
Hello,
installation of gdata does not always work. Please check if gdata is correctly installed in your system und install it seperatly, if necessary
`pip install gdata`

**Pull request merged**
